name: filcnaplo_mobile_ui
publish_to: "none"

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Filcnaplo main dep
  filcnaplo:
    path: ../filcnaplo/
  filcnaplo_kreta_api:
    path: ../filcnaplo_kreta_api/

  flutter_feather_icons: ^2.0.0+1
  provider: ^5.0.0
  fl_chart: ^0.45.1
  url_launcher: ^6.0.9
  flutter_material_color_picker: ^1.1.0+2
  photo_view: ^0.13.0
  flutter_linkify: ^5.0.2
  flutter_custom_tabs: ^1.0.3
  flutter_markdown: ^0.6.5
  animations: ^2.0.1
  implicitly_animated_reorderable_list: ^0.4.1
  sliding_sheet: ^0.5.2
  confetti: ^0.6.0
  live_activities: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
